name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Create testdata
      run: make testdata

    - name: Test
      run: |
        go test -v ./cmd/...  ./validate/... -cover -coverprofile=.cover
        grep -v .pb.go .cover > cover.out

    - uses: actions/cache@v2
      with:
        path: cover.out
        key: coverage
  
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/cache@v2
      with:
        path: cover.out
        key: coverage
    
    - name: Convert coverage to lcov
      run: |
        go install github.com/jandelgado/gcov2lcov@latest
        GOROOT=$(go env GOROOT) gcov2lcov -infile=cover.out -outfile=coverage.lcov
      
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
