name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/...

    - name: Test
      run: |
        go test -v ./cmd/... ./gateway/...  ./validate/... -cover -coverprofile=.cover
        grep -v .pb.go cover.out > cover.out

    - uses: actions/cache@v2
      with:
        path: cover.out
  
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/cache@v2
      with:
        path: cover.out
    
    - name: Convert coverage to lcov
      run: |
        go install github.com/jandelgado/gcov2lcov@latest
        GOROOT=$(go env GOROOT) gcov2lcov -infile=cover.out -outfile=coverage.lcov
      
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
